export type Airframes = {
    A148: AirframeAircraft
    A225: AirframeAircraft
    BCS1: AirframeAircraft
    BCS3: AirframeAircraft
    A306: AirframeAircraft
    A3ST: AirframeAircraft
    A30B: AirframeAircraft
    A30F: AirframeAircraft
    A310: AirframeAircraft
    A318: AirframeAircraft
    A319: AirframeAircraft
    A320: AirframeAircraft
    A20N: AirframeAircraft
    A321: AirframeAircraft
    A21N: AirframeAircraft
    A332: AirframeAircraft
    A333: AirframeAircraft
    A338: AirframeAircraft
    A339: AirframeAircraft
    A342: AirframeAircraft
    A343: AirframeAircraft
    A345: AirframeAircraft
    A346: AirframeAircraft
    A359: AirframeAircraft
    A35K: AirframeAircraft
    A388: AirframeAircraft
    AEST: AirframeAircraft
    AT43: AirframeAircraft
    AT45: AirframeAircraft
    AT46: AirframeAircraft
    AT72: AirframeAircraft
    AT73: AirframeAircraft
    AT75: AirframeAircraft
    AT76: AirframeAircraft
    B190: AirframeAircraft
    B350: AirframeAircraft
    B461: AirframeAircraft
    B462: AirframeAircraft
    B463: AirframeAircraft
    B703: AirframeAircraft
    B712: AirframeAircraft
    B721: AirframeAircraft
    B722: AirframeAircraft
    R722: AirframeAircraft
    B732: AirframeAircraft
    B733: AirframeAircraft
    B734: AirframeAircraft
    B735: AirframeAircraft
    B736: AirframeAircraft
    B737: AirframeAircraft
    BBJ1: AirframeAircraft
    B738: AirframeAircraft
    BBJ2: AirframeAircraft
    B38M: AirframeAircraft
    B739: AirframeAircraft
    BBJ3: AirframeAircraft
    B741: AirframeAircraft
    B742: AirframeAircraft
    B744: AirframeAircraft
    B74F: AirframeAircraft
    B748: AirframeAircraft
    B48F: AirframeAircraft
    B752: AirframeAircraft
    B75F: AirframeAircraft
    B753: AirframeAircraft
    B762: AirframeAircraft
    B763: AirframeAircraft
    B76F: AirframeAircraft
    B764: AirframeAircraft
    B772: AirframeAircraft
    B77F: AirframeAircraft
    B77L: AirframeAircraft
    B77W: AirframeAircraft
    B788: AirframeAircraft
    B789: AirframeAircraft
    B78X: AirframeAircraft
    BE9L: AirframeAircraft
    BE20: AirframeAircraft
    BE24: AirframeAircraft
    BE36: AirframeAircraft
    BT36: AirframeAircraft
    B36T: AirframeAircraft
    BE58: AirframeAircraft
    B58T: AirframeAircraft
    BE60: AirframeAircraft
    BE6G: AirframeAircraft
    B60T: AirframeAircraft
    C130: AirframeAircraft
    BN2P: AirframeAircraft
    C160: AirframeAircraft
    C17: AirframeAircraft
    C172: AirframeAircraft
    C182: AirframeAircraft
    R182: AirframeAircraft
    C208: AirframeAircraft
    C310: AirframeAircraft
    C337: AirframeAircraft
    C404: AirframeAircraft
    C408: AirframeAircraft
    C414: AirframeAircraft
    C46: AirframeAircraft
    C510: AirframeAircraft
    C525: AirframeAircraft
    C25A: AirframeAircraft
    C25B: AirframeAircraft
    C25C: AirframeAircraft
    C550: AirframeAircraft
    C56X: AirframeAircraft
    C680: AirframeAircraft
    C700: AirframeAircraft
    C750: AirframeAircraft
    C919: AirframeAircraft
    CL30: AirframeAircraft
    CL35: AirframeAircraft
    CL60: AirframeAircraft
    CONI: AirframeAircraft
    CONS: AirframeAircraft
    CRJ2: AirframeAircraft
    CRJ5: AirframeAircraft
    CRJ7: AirframeAircraft
    CRJ9: AirframeAircraft
    CRJX: AirframeAircraft
    D328: AirframeAircraft
    DA42: AirframeAircraft
    DA62: AirframeAircraft
    DC10: AirframeAircraft
    DC3: AirframeAircraft
    DC6: AirframeAircraft
    DC85: AirframeAircraft
    DC86: AirframeAircraft
    DH8A: AirframeAircraft
    DH8B: AirframeAircraft
    DH8C: AirframeAircraft
    DH8D: AirframeAircraft
    DHC2: AirframeAircraft
    DHC6: AirframeAircraft
    DHC7: AirframeAircraft
    E135: AirframeAircraft
    E13L: AirframeAircraft
    E140: AirframeAircraft
    E145: AirframeAircraft
    E170: AirframeAircraft
    E175: AirframeAircraft
    E190: AirframeAircraft
    E19L: AirframeAircraft
    E195: AirframeAircraft
    E50P: AirframeAircraft
    E55P: AirframeAircraft
    EA50: AirframeAircraft
    EVAL: AirframeAircraft
    F28: AirframeAircraft
    F50: AirframeAircraft
    F70: AirframeAircraft
    F100: AirframeAircraft
    F406: AirframeAircraft
    FA50: AirframeAircraft
    FA8X: AirframeAircraft
    GLF4: AirframeAircraft
    GLF6: AirframeAircraft
    H25B: AirframeAircraft
    HDJT: AirframeAircraft
    IL76: AirframeAircraft
    JS41: AirframeAircraft
    KODI: AirframeAircraft
    L101: AirframeAircraft
    L410: AirframeAircraft
    LJ25: AirframeAircraft
    LJ35: AirframeAircraft
    LJ45: AirframeAircraft
    MD11: AirframeAircraft
    MD1F: AirframeAircraft
    MD82: AirframeAircraft
    MD83: AirframeAircraft
    MD88: AirframeAircraft
    MD90: AirframeAircraft
    MU2: AirframeAircraft
    P06T: AirframeAircraft
    P180: AirframeAircraft
    P212: AirframeAircraft
    P46T: AirframeAircraft
    M600: AirframeAircraft
    PA24: AirframeAircraft
    PA34: AirframeAircraft
    PA44: AirframeAircraft
    PC12: AirframeAircraft
    PC24: AirframeAircraft
    RJ70: AirframeAircraft
    RJ85: AirframeAircraft
    RJ1H: AirframeAircraft
    SB20: AirframeAircraft
    SF34: AirframeAircraft
    SF50: AirframeAircraft
    SH33: AirframeAircraft
    SH36: AirframeAircraft
    SR22: AirframeAircraft
    SR2T: AirframeAircraft
    STAR: AirframeAircraft
    SU95: AirframeAircraft
    SW4: AirframeAircraft
    T134: AirframeAircraft
    T154: AirframeAircraft
    T204: AirframeAircraft
    TBM8: AirframeAircraft
    TBM9: AirframeAircraft
    VC10: AirframeAircraft
    YK40: AirframeAircraft
    YK42: AirframeAircraft
    YS11: AirframeAircraft
}

export type AirframeAircraft = {
    aircraft_id: string
    aircraft_icao: string
    aircraft_name: string
    aircraft_sort: string
    aircraft_engines: string
    aircraft_search: string
    aircraft_passengers: number
    aircraft_mtow_lbs: number
    aircraft_mtow_kgs: number
    aircraft_speed: string
    aircraft_ceiling: number
    aircraft_takeoff: number
    aircraft_landing: number
    aircraft_thrust_lbf: number
    aircraft_thrust_shp: boolean
    aircraft_thrust_flat_rating: number
    aircraft_max_costindex: number
    aircraft_fuelflow_lbs: number
    aircraft_fuelflow_kgs: number
    aircraft_is_cargo: boolean
    aircraft_diversion_distance: number
    aircraft_profiles_climb: string[]
    aircraft_profiles_cruise: string[]
    aircraft_profiles_descent: string[]
    aircraft_profiles_takeoff_flaps: string[]
    aircraft_profiles_takeoff_thrust: string[]
    aircraft_profiles_takeoff_thrust_names: string[]
    aircraft_profiles_takeoff_bleeds: string[]
    aircraft_profiles_takeoff_antice: string[]
    aircraft_profiles_landing_flaps: string[]
    aircraft_profiles_landing_brakes: string[]
    aircraft_profiles_landing_reverse: string[]
    aircraft_default_cruise: string
    stats_updated: string
    stats_accuracy: boolean
    stats_popularity: number
    stats_charts: boolean
    stats_costindex: boolean
    stats_tlr: boolean
    stats_flex: boolean
    stats_is_custom: boolean
    airframes: Airframe[]
}

export type Airframe = {
    airframe_id: number
    user_id: string
    pilot_id: number
    modified_time: string
    airframe_internal_id: string
    airframe_base_type: string
    airframe_list_type: string
    airframe_icao: string
    airframe_name: string
    airframe_engines: string
    airframe_registration: string
    airframe_fin: string
    airframe_passengers: number
    airframe_comments: string
    airframe_options: AirframeOptions
}

export type AirframeOptions = {
    basetype: string
    icao: string
    reg: string
    fin: string
    selcal: string
    hexcode: string
    name: string
    engines: string
    comments: string
    cat: string
    per: string
    equip: string
    transponder: string
    pbn: string
    extrarmk: string
    wgtunits: string
    maxpax: string
    paxwgt: number
    bagwgt: number
    oew: number
    mzfw: number
    mtow: number
    mlw: number
    maxfuel: number
    maxcargo: number
    defaultcruise: string
    defaultci: string
    defaultclimb: string
    defaultdescent: string
    fuelfactor: string
    ceiling: string
    thrust: string
    thrust_units: string
    flatrating: string
    cruiseoffset: string
    etopsthreshold: string
    etopsrange: string
    planunits: string
    cargomode: string
    planformat: string
    flightrules: string
    flighttype: string
    altnsadv_radius: string
    altnsadv_rwy: string
    altnsadv_units_rwy: string
    manualrmk: string
    contpct: string
    resvrule: string
    taxifuel: string
    minfob: string
    minfod: string
    melfuel: string
    atcfuel: string
    wxxfuel: string
    addedfuel: string
    tankering: string
    minfob_units: string
    minfod_units: string
    melfuel_units: string
    atcfuel_units: string
    wxxfuel_units: string
    addedfuel_units: string
    tankering_units: string
    addedfuel_label: string
}
